# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoAmazing' do

use_frameworks!

pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod "GPUImage"
	

end
